### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by nathanshelly** [natasha-codes/snek#7]
Using [cargo-husky](https://github.com/rhysd/cargo-husky)?

**Comment by sashaweiss** [comment]
not sold on this - `cargo test` can take a hot minute to run, and we already have CI to run tests. Plus - there are scenarios where I want to push broken tests - e.g. I'm working on a branch and added a bunch of test skeletons but haven't implemented them yet.

could see us adding for clippy, but same argument applies - sometimes i *want* to push broken/bad stuff.

tl;dr I wonder if this is something we can rely on CI for rather than hooks.

**Comment by nathanshelly** [comment]
Discussed separately

Definitely agree we shouldn't do `cargo test` as a pre-commit hook. Thinking of having `rustfmt` & `clippy` pre-commit hooks.

Also, if you want to skip the hook - `git commit --no-verify`

**Comment by sashaweiss** [comment]
lol `prettier`

edit: for the record, @nathanshelly originally wrote `prettier` instead of `rustfmt`

**Comment by sashaweiss** [comment]
`rustfmt` and `clippy` are fine by me.

**Comment by nathanshelly** [comment]
whoops 🤦‍♂

**Comment by sashaweiss** [comment]
Closed by #8
